@startuml "Diagrama de clase"
left to right direction

Class Usuario {
    #id : Integer
    #nombre : String
    #apellido : String
    #email : String
    #clave_encriptada : String
}

Class Pictograma {
    #id: Integer
    #nombre : String
    #imagen: String
    #aarasac_id: Integer
    #funcion_sintactica: Integer
}

Class Categoria {
    #id: Integer
    #nombre : String
    #nombre_ingles: String
}

Class Pictograma_Categoria {
    #categoria_id: Integer
    #pictograma_id: Integer
}

Class Prediccion_Pictograma {
	#id: Integer
	#pictograma_ids: String
	#peso: Integer
}

Class Prediccion_Sintáctica {
	#id: Integer
	#tipoInicial: String
	#proximoTipo: String
	#peso: Integer
}

Class Frase_Usada {
	#id: Integer
	#pictograma_ids: String
	#peso: Integer
	#usuario_id: Integer
}

Class Frase_Usada_Dw {
	#peso: Integer
	#pictograma_ids: String
}

Frase_Usada "0..*" -- "1" Usuario
Pictograma_Categoria "0..*" -- "0..*" Categoria
Pictograma_Categoria "0..*" -- "0..*" Pictograma
Prediccion_Pictograma "0..*" -- "1" Pictograma
Frase_Usada "0..*" -- "1" Pictograma
Frase_Usada "0..*" -- "1" Frase_Usada_Dw 
@enduml