@startuml "Diagrama de clase"
left to right direction

Class Usuario {
    #id : Integer
    #nombre : String
    #apellido : String
    #email : String
    #password : String
}

Class Pictograma {
    #id: Integer
    #nombre : String
    #imagen: String
    #categoria: Categoria
    #funcionSintactica: String
}

Class Categoria {
    #id: Integer
    #nombre : String
    #carpeta: String
}

Class PrediccionPictograma {
	#id: Integer
	#fraseInicial: ArrayList<FraseInicial>
	#proximoPictograma: Pictograma
	#peso: Integer
	#usuario: Usuario
}

Class FraseInicial {
	#id: Integer
	#pictograma: Pictograma
	#orden: Integer
}

Class PrediccionSintáctica {
	#id: Integer
	#tipoInicial: String
	#proximoTipo: String
	#peso: Integer
}

Class FraseUsada {
	#id: Integer
	#pictograma: Pictograma
	#orden: Integer
	#usuario: Usuario
}

Pictograma "1" -- "0..*" Categoria
PrediccionPictograma "0..*" -- "1" Pictograma
PrediccionPictograma "0..*" -- "0..*" FraseInicial
PrediccionPictograma "0..*" -- "0..1" Usuario 
FraseUsada "0..*" -- "1" Pictograma
FraseUsada "0..*" -- "1" Usuario 
@enduml